### ISSUE TITLE
Support RSpec

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-annotations#10]
Helpful for Ruby specs (tests)

https://rspec.info/

**Comment by fkorotkov** [comment]
Do you have an example of RSpec report file?

**Comment by AlexWayfer** [comment]
> Do you have an example of RSpec report file?

I can create a new one. Do you need for a file or standard output is enough?

**Comment by AlexWayfer** [comment]
Successful output with default formatter:

```
......................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 0.36845 seconds (files took 1.23 seconds to load)
422 examples, 0 failures
```

With `--format=doc` we have something like:

```
Flame::Validators
  Flame::Validators::RouteArgumentsValidator
    #valid?
      no extra arguments
        is expected to equal true
      extra action required arguments
        is expected to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:?third/:?fourth' has no required arguments [:second]"
      extra action optional arguments
        is expected to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:second' has no optional arguments [:third, :fourth]"
      extra path required arguments
        is expected to raise Flame::Errors::RouteExtraArgumentsError with "Action 'ValidatorsController#foo' has no required arguments [:fourth]"
      extra path optional arguments
        is expected to raise Flame::Errors::RouteExtraArgumentsError with "Action 'ValidatorsController#foo' has no optional arguments [:fifth]"
      wrong order of optional arguments
        is expected to raise Flame::Errors::RouteArgumentsOrderError with "Path '/foo/:first/:second/:?fourth/:?third' should have ':?third' argument before ':?fourth'"

5.0.0.rc5
  is expected to be a kind of String
  is expected not to be empty

Finished in 0.17502 seconds (files took 0.38417 seconds to load)
422 examples, 0 failures
```

With failures:

```
Flame::Router
  #app
    is expected to be < Flame::Application
  #routes
    is expected to be an instance of Flame::Router::Routes
  #reverse_routes
    is expected to be an instance of Integer (FAILED - 1)
  #initialize
    #routes
      is expected to be an instance of Flame::Router::Routes
      is expected to be any (FAILED - 2)
    #reverse_routes
      is expected to be an instance of Hash
      is expected to be any (FAILED - 3)
  #find_nearest_route
    one mounted controller
      existing controller and action
        is expected to eq "RouterTest::OneController#foo"
      nonexistent action
        is expected to eq "RouterTest::OneController#index"
      path without optional argument
        is expected to eq "RouterTest::OneController#foo"
      nonexistent route
        is expected to be true (FAILED - 4)
      path without required argument
        is expected to eq "RouterTest::OneController#foo" (FAILED - 5)
    controller with nested controller
      is expected to eq "RouterTest::OneController#index"
  #path_of
    existing route
      by route
        behaves like route found
          is expected to eq "/one/foo/:first/:second/:?third/:?fourth"
      by controller and action
        behaves like route found
          is expected to eq "/one/foo/:first/:second/:?third/:?fourth"
    nonexistent route
      is expected to be nil

Flame::Validators
  Flame::Validators::RouteArgumentsValidator
    #valid?
      no extra arguments
        is expected to equal false (FAILED - 6)
      extra action required arguments
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass, message)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /home/alex/Projects/ruby/flame/spec/unit/validators_spec.rb:27:in `block (5 levels) in <top (required)>'.
        is expected not to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:?third/:?fourth' has no required arguments [:second]" (FAILED - 7)
      extra action optional arguments
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass, message)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /home/alex/Projects/ruby/flame/spec/unit/validators_spec.rb:38:in `block (5 levels) in <top (required)>'.
        is expected not to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:second' has no optional arguments [:third, :fourth]" (FAILED - 8)
      extra path required arguments
        is expected to raise Flame::Errors::RouteExtraArgumentsError with "Action 'ValidatorsController#foo' has no required arguments [:fourth]"
      extra path optional arguments
        is expected to raise Flame::Errors::RouteExtraArgumentsError with "Action 'ValidatorsController#foo' has no optional arguments [:fifth]"
      wrong order of optional arguments
        is expected to raise Flame::Errors::RouteArgumentsOrderError with "Path '/foo/:first/:second/:?fourth/:?third' should have ':?third' argument before ':?fourth'"

5.0.0.rc5
  is expected to be a kind of String
  is expected not to be empty

Failures:

  1) Flame::Router#reverse_routes is expected to be an instance of Integer
     Failure/Error: it { is_expected.to be_instance_of Integer }
       expected {} to be an instance of Integer
     # ./spec/unit/router_spec.rb:38:in `block (3 levels) in <top (required)>'

  2) Flame::Router#initialize #routes is expected to be any
     Failure/Error: it { is_expected.to be_any }
       expected `{}.any?` to return true, got false
     # ./spec/unit/router_spec.rb:46:in `block (4 levels) in <top (required)>'

  3) Flame::Router#initialize #reverse_routes is expected to be any
     Failure/Error: it { is_expected.to be_any }
       expected `{}.any?` to return true, got false
     # ./spec/unit/router_spec.rb:53:in `block (4 levels) in <top (required)>'

  4) Flame::Router#find_nearest_route one mounted controller nonexistent route is expected to be true
     Failure/Error: is_expected.to be_true
       expected nil to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/unit/router_spec.rb:101:in `block (5 levels) in <top (required)>'

  5) Flame::Router#find_nearest_route one mounted controller path without required argument is expected to eq "RouterTest::OneController#foo"
     Failure/Error:
       is_expected.to eq Flame::Router::Route.new(
       	RouterTest::OneController, :foo
       )
     
       expected: "RouterTest::OneController#foo"
            got: "RouterTest::OneController#index"
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -"RouterTest::OneController#foo"
       +"RouterTest::OneController#index"
       
     # ./spec/unit/router_spec.rb:109:in `block (5 levels) in <top (required)>'

  6) Flame::Validators Flame::Validators::RouteArgumentsValidator#valid? no extra arguments is expected to equal false
     Failure/Error: it { is_expected.to be false }
     
       expected false
            got true
     # ./spec/unit/validators_spec.rb:20:in `block (5 levels) in <top (required)>'

  7) Flame::Validators Flame::Validators::RouteArgumentsValidator#valid? extra action required arguments is expected not to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:?third/:?fourth' has no required arguments [:second]"
     Failure/Error:
       expect { subject }.not_to raise_error(
       	Flame::Errors::RouteExtraArgumentsError,
       	"Path '#{path}' has no required arguments [:second]"
       )
     
       expected no Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:?third/:?fourth' has no required arguments [:second]", got #<Flame::Errors::RouteExtraArgumentsError: Path '/foo/:first/:?third/:?fourth' has no required arguments [:second]> with backtrace:
         # ./lib/flame/validators.rb:33:in `extra_valid?'
         # ./lib/flame/validators.rb:23:in `valid?'
         # ./spec/unit/validators_spec.rb:15:in `block (4 levels) in <top (required)>'
         # ./spec/unit/validators_spec.rb:27:in `block (6 levels) in <top (required)>'
         # ./spec/unit/validators_spec.rb:27:in `block (5 levels) in <top (required)>'
     # ./spec/unit/validators_spec.rb:27:in `block (5 levels) in <top (required)>'

  8) Flame::Validators Flame::Validators::RouteArgumentsValidator#valid? extra action optional arguments is expected not to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:second' has no optional arguments [:third, :fourth]"
     Failure/Error:
       expect { subject }.not_to raise_error(
       	Flame::Errors::RouteExtraArgumentsError,
       	"Path '#{path}' has no optional arguments [:third, :fourth]"
       )
     
       expected no Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:second' has no optional arguments [:third, :fourth]", got #<Flame::Errors::RouteExtraArgumentsError: Path '/foo/:first/:second' has no optional arguments [:third, :fourth]> with backtrace:
         # ./lib/flame/validators.rb:33:in `extra_valid?'
         # ./lib/flame/validators.rb:23:in `valid?'
         # ./spec/unit/validators_spec.rb:15:in `block (4 levels) in <top (required)>'
         # ./spec/unit/validators_spec.rb:38:in `block (6 levels) in <top (required)>'
         # ./spec/unit/validators_spec.rb:38:in `block (5 levels) in <top (required)>'
     # ./spec/unit/validators_spec.rb:38:in `block (5 levels) in <top (required)>'

Finished in 0.23504 seconds (files took 0.36736 seconds to load)
422 examples, 8 failures

Failed examples:

rspec ./spec/unit/router_spec.rb:38 # Flame::Router#reverse_routes is expected to be an instance of Integer
rspec ./spec/unit/router_spec.rb:46 # Flame::Router#initialize #routes is expected to be any
rspec ./spec/unit/router_spec.rb:53 # Flame::Router#initialize #reverse_routes is expected to be any
rspec ./spec/unit/router_spec.rb:100 # Flame::Router#find_nearest_route one mounted controller nonexistent route is expected to be true
rspec ./spec/unit/router_spec.rb:108 # Flame::Router#find_nearest_route one mounted controller path without required argument is expected to eq "RouterTest::OneController#foo"
rspec ./spec/unit/validators_spec.rb:20 # Flame::Validators Flame::Validators::RouteArgumentsValidator#valid? no extra arguments is expected to equal false
rspec ./spec/unit/validators_spec.rb:26 # Flame::Validators Flame::Validators::RouteArgumentsValidator#valid? extra action required arguments is expected not to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:?third/:?fourth' has no required arguments [:second]"
rspec ./spec/unit/validators_spec.rb:37 # Flame::Validators Flame::Validators::RouteArgumentsValidator#valid? extra action optional arguments is expected not to raise Flame::Errors::RouteExtraArgumentsError with "Path '/foo/:first/:second' has no optional arguments [:third, :fourth]"
```

Do you need for something else?

**Comment by fkorotkov** [comment]
Does `--format` support some format that is more machine readable? Like JSON or XML?

**Comment by AlexWayfer** [comment]
> Does `--format` support some format that is more machine readable? Like JSON or XML?

```
  **** Output ****

    -f, --format FORMATTER             Choose a formatter.
                                         [p]rogress (default - dots)
                                         [d]ocumentation (group and example names)
                                         [h]tml
                                         [j]son
                                         [f]ailures ("file:line:reason", suitable for editors integration)
                                         custom formatter class name
    -o, --out FILE                     Write output to a file instead of $stdout. This option applies
                                         to the previously specified --format, or the default format
                                         if no format is specified.
        --deprecation-out FILE         Write deprecation warnings to a file instead of $stderr.
    -b, --backtrace                    Enable full backtrace.
        --force-color, --force-colour  Force the output to be in color, even if the output is not a TTY
        --no-color, --no-colour        Force the output to not be in color, even if the output is a TTY
    -p, --[no-]profile [COUNT]         Enable profiling of examples and list the slowest examples (default: 10).
        --dry-run                      Print the formatter output of your suite without
                                         running any examples or hooks
    -w, --warnings                     Enable ruby warnings
```

So, here the output with `json` format: … oh, it's a huge! Let's attache a file.

[rspec_json_output.txt](https://github.com/cirruslabs/cirrus-ci-annotations/files/4405242/rspec_json_output.txt)

Please, pay attention, that there are also Ruby-warnings (only at the start, I guess) and `Coverage report` at the end.

**Comment by rciovati** [comment]
my 2 cents: it seems that here are rspec plugins to format the output as a junit report (that this project already support). I'm not familiar with those library, but perhaps it makes sense to use one of them?

**Comment by fkorotkov** [comment]
This is working now 🎉 Thanks, @edigaryev!

**Comment by AlexWayfer** [comment]
Thank you!

**Comment by AlexWayfer** [comment]
It seems not working:

https://github.com/AlexWayfer/gem_toys/pull/12/files

![image](https://user-images.githubusercontent.com/6510020/87668069-22129b80-c774-11ea-8505-0c795bbbcee6.png)

https://cirrus-ci.com/build/6037101353369600

![image](https://user-images.githubusercontent.com/6510020/87668113-32c31180-c774-11ea-9ac2-2c768b6c9134.png)

**Comment by edigaryev** [comment]
>https://github.com/AlexWayfer/gem_toys/pull/12/files

Looks like the annotation is generated here:

https://github.com/AlexWayfer/gem_toys/pull/12/checks?check_run_id=877428011

But it doesn't get attached to the proper file in the "Files changed" tab.

It seems that GitHub does not normalize annotation paths like `./spec/gem_toys/version_spec.rb` into `spec/gem_toys/version_spec.rb` and simply matches them as is.

**Comment by AlexWayfer** [comment]
@edigaryev thank you for explanation and PR.
